lib/plenario_web/router.ex
defmodule PlenarioWeb.Router do
  use PlenarioWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :maybe_auth do
    plug PlenarioWeb.AuthPipeline
    plug PlenarioWeb.CurrentUserPlug
  end

  pipeline :ensure_auth do
    plug PlenarioWeb.AuthPipeline
    plug Guardian.Plug.EnsureAuthenticated
    plug PlenarioWeb.CurrentUserPlug
  end

  pipeline :admin do
    plug PlenarioWeb.AuthPipeline
    plug Guardian.Plug.EnsureAuthenticated
    plug PlenarioWeb.EnsureAdminPlug
    plug PlenarioWeb.CurrentUserPlug
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", PlenarioWeb do
    pipe_through ~w|browser ensure_auth|a

    # me controller
    get "/me",        MeController, :show
    get "/me/edit",   MeController, :edit
    put "/me/update", MeController, :update

    # data sets
    resources "/data-sets", DataSetController, only: ~w|new create edit update delete|a
    post "/data-sets/:id/submit-for-approval", DataSetController, :submit_for_approval
    post "/data-sets/:id/reload-fields", DataSetController, :reload_fields
    post "/data-sets/:id/ingest-now", DataSetController, :ingest_now

    # data set nested resources: fields, virtual dates and virtual points
    resources "/data-sets", DataSetController do
      # fields
      resources "/fields", FieldController, only: ~w|edit update delete|a
      # virtual dates
      resources "/virtual-dates", VirtualDateController, only: ~w|new create edit update delete|a
      # virtual points
      resources "/virtual-points", VirtualPointController, only: ~w|new create edit update delete|a
    end
  end

  scope "/", PlenarioWeb do
    pipe_through ~w|browser maybe_auth|a

    # flat page
    get "/", PageController, :index
    get "/explorer", PageController, :explorer

    # sessions
    get   "/login",     SessionController, :login
    post  "/login",     SessionController, :login
    get   "/register",  SessionController, :register
    post  "/register",  SessionController, :register
    post  "/logout",    SessionController, :logout

    # data sets
    get "/data-sets/:id", DataSetController, :show
  end

  scope "/admin", PlenarioWeb do
    pipe_through ~w|browser admin|a

    get "/", PageAdminController, :index

    resources "/users", UserAdminController

    get "/data-sets",               DataSetAdminController, :index
    get "/data-sets/:id/review",    DataSetAdminController, :review
    post "/data-sets/:id/approve",  DataSetAdminController, :approve
    post "/data-sets/:id/reject",   DataSetAdminController, :reject
  end

  scope "/api/v2", PlenarioWeb do
    pipe_through [:api]

    get "/data-sets", DataSetApiController, :list
    get "/data-sets/:slug", DataSetApiController, :detail
    get "/data-sets/:slug/@aggregate", DataSetApiController, :aggregate
  end
end

lib/plenario/actions/data_set_actions.ex
defmodule Plenario.DataSetActions do
  import Plenario.ActionUtils

  alias Plenario.{
    DataSet,
    DataSetQueries,
    FieldActions,
    Repo,
    VirtualDateActions,
    VirtualPointActions
  }

  # CRUD

  def list(opts \\ []) do
    DataSetQueries.list()
    |> DataSetQueries.handle_opts(opts)
    |> Repo.all()
  end

  def get(id, opts \\ []) do
    ds =
      DataSetQueries.get(id)
      |> DataSetQueries.handle_opts(opts)
      |> Repo.one()

    case ds do
      nil -> {:error, nil}
      _ -> {:ok, ds}
    end
  end

  def get!(id, opts \\ []) do
    DataSetQueries.get(id)
    |> DataSetQueries.handle_opts(opts)
    |> Repo.one!()
  end

  def create(params) do
    params =
      params_to_map(params)
      |> parse_relation(:user)

    DataSet.changeset(%DataSet{}, params)
    |> Repo.insert()
  end

  def update(ds, params) do
    params =
      params_to_map(params)
      |> parse_relation(:user)

    DataSet.changeset(ds, params)
    |> Repo.update()
  end

  def delete(ds), do: Repo.delete(ds)

  # Other Actions

  def compute_next_import!(%DataSet{refresh_rate: nil}, _), do: nil
  def compute_next_import!(%DataSet{refresh_interval: nil}, _), do: nil
  def compute_next_import!(%DataSet{refresh_interval: interval, refresh_rate: rate}, last) do
    Timex.shift(last, [{String.to_atom(interval), rate}])
    |> Timex.to_naive_datetime()
  end

  def compute_bbox!(%DataSet{} = ds) do
    field_names = get_geom_fields(ds)

    query = """
    SELECT st_envelope(#{field_names})
    FROM "#{ds.view_name}"
    """

    %Postgrex.Result{rows: [[bbox]], num_rows: 1} = Repo.query!(query)
    bbox
  end

  def compute_hull!(%DataSet{} = ds) do
    field_names = get_geom_fields(ds)

    query = """
    SELECT st_convexhull(#{field_names})
    FROM "#{ds.view_name}"
    """

    %Postgrex.Result{rows: [[hull]], num_rows: 1} = Repo.query!(query)
    hull
  end

  defp get_geom_fields(ds) do
    fields =
      FieldActions.list(for_data_set: ds)
      |> Enum.filter(& &1.type == "geometry")
      |> Enum.map(& &1.col_name)

    points =
      VirtualPointActions.list(for_data_set: ds)
      |> Enum.map(& &1.col_name)

    names =
      (fields ++ points)
      |> Enum.join("\", \"")

    case length((fields ++ points)) do
      1 -> "st_union(\"#{names}\")"
      _ -> "st_union(st_collect(\"#{names}\"))"
    end
  end

  def compute_time_range!(%DataSet{} = ds) do
    fields =
      FieldActions.list(for_data_set: ds)
      |> Enum.filter(& &1.type == "timestamp")
      |> Enum.map(& &1.col_name)

    dates =
      VirtualDateActions.list(for_data_set: ds)
      |> Enum.map(& &1.col_name)

    field_names =
      (fields ++ dates)
      |> Enum.join("\", \"")

    query = """
    SELECT
      MIN( LEAST("#{field_names}")) AS lower,
      MAX( GREATEST("#{field_names}")) AS upper
    FROM "#{ds.view_name}"
    """

    %Postgrex.Result{rows: [[lower, upper]], num_rows: 1} = Repo.query!(query)

    case is_nil(lower) or is_nil(upper) do
      true -> nil
      false -> Plenario.TsRange.new(lower, upper)
    end
  end

  def get_num_records!(%DataSet{} = ds) do
    query = """
    SELECT COUNT(*)
    FROM "#{ds.view_name}"
    """

    %Postgrex.Result{rows: [[count]], num_rows: 1} = Repo.query!(query)

    case count do
      0 -> nil
      _ -> count
    end
  end
end

lib/plenario_web/controllers/data_set_controller.ex
defmodule PlenarioWeb.DataSetController do
  use PlenarioWeb, :controller

  require Logger

  alias Plenario.{
    Auth.Guardian,
    DataSet,
    DataSetActions,
    Etl,
    FieldActions,
    VirtualDateActions,
    VirtualPointActions
  }

  plug :authorize_resource, model: DataSet

  # CRUD

  def new(conn, %{"name" => name, "socrata" => soc?}) do
    soc? = if soc? == "true", do: true, else: false

    changeset = DataSet.changeset(%DataSet{}, %{
      name: name,
      socrata?: soc?,
      state: "new",
      user_id: Plenario.Auth.Guardian.Plug.current_resource(conn).id
    })

    create_action = Routes.data_set_path(conn, :create)
    backout_action = Routes.me_path(conn, :show)

    render conn, "new.html",
      changeset: changeset,
      socrata?: soc?,
      fully_editable?: true,
      create_action: create_action,
      backout_action: backout_action
  end

  def new(conn, params) when params == %{}, do: render conn, "init.html", action: Routes.data_set_path(conn, :new)

  def create(conn, %{"data_set" => form}) do
    DataSetActions.create(form)
    |> do_create(conn)
  end

  defp do_create({:ok, data_set}, conn) do
    try do
      Logger.info("attempting to create fields for #{data_set.name}")
      {:ok, _} = FieldActions.create_for_data_set(data_set)
    rescue
      e in Exception ->
        Logger.error(e.message)
    end

    conn
    |> put_flash(:success, "Created #{data_set.name}")
    |> redirect(to: Routes.data_set_path(conn, :show, data_set))
  end

  defp do_create({:error, changeset}, conn) do
    socrata? = Ecto.Changeset.get_field(changeset, :socrata?)
    create_action = Routes.data_set_path(conn, :create)
    backout_action = Routes.me_path(conn, :show)

    Logger.debug("#{inspect(changeset)}")

    conn
    |> put_status(:bad_request)
    |> put_error_flashes(changeset)
    |> render("new.html",
      changeset: changeset,
      socrata?: socrata?,
      fully_editable?: true,
      create_action: create_action,
      backout_action: backout_action
    )
  end

  def show(conn, %{"id" => id}) do
    user = Guardian.Plug.current_resource(conn)
    data_set = DataSetActions.get!(id, with_user: true, with_fields: true)

    user_is_owner? = user.is_admin? or data_set.user_id == user.id
    ok_to_import? = not Enum.member?(["new", "awaiting_approval", "erred"], data_set.state)
    submittable? = data_set.state == "new"

    render conn, "show.html",
      data_set: data_set,
      user_is_owner?: user_is_owner?,
      ok_to_import?: ok_to_import?,
      submittable?: submittable?,
      virtual_dates: VirtualDateActions.list(for_data_set: data_set, with_fields: true),
      virtual_points: VirtualPointActions.list(for_data_set: data_set, with_fields: true)
  end

  def edit(conn, %{"id" => id}) do
    data_set = DataSetActions.get!(id)
    changeset = DataSet.changeset(data_set, %{})
    fully_editable? = data_set.state == "new"

    update_action = Routes.data_set_path(conn, :update, data_set)
    backout_action = Routes.data_set_path(conn, :show, data_set)

    render conn, "edit.html",
      data_set: data_set,
      changeset: changeset,
      fully_editable?: fully_editable?,
      update_action: update_action,
      backout_action: backout_action
  end

  def update(conn, %{"id" => id, "data_set" => form}) do
    data_set = DataSetActions.get!(id)

    DataSetActions.update(data_set, form)
    |> do_update(conn, data_set)
  end

  defp do_update({:ok, data_set}, conn, _) do
    conn
    |> put_flash(:success, "Updated #{data_set.name}")
    |> redirect(to: Routes.data_set_path(conn, :show, data_set))
  end

  defp do_update({:error, changeset}, conn, data_set) do
    update_action = Routes.data_set_path(conn, :update, data_set)
    backout_action = Routes.data_set_path(conn, :show, data_set)
    fully_editable? = data_set.state == "new"

    conn
    |> put_status(:bad_request)
    |> put_error_flashes(changeset)
    |> render("edit.html",
      data_set: data_set,
      changeset: changeset,
      fully_editable?: fully_editable?,
      update_action: update_action,
      backout_action: backout_action
    )
  end

  def delete(conn, %{"id" => id}) do
    data_set = DataSetActions.get!(id)
    {:ok, _} = DataSetActions.delete(data_set)

    conn
    |> put_flash(:info, "Deleted #{data_set.name}")
    |> redirect(to: Routes.me_path(conn, :show))
  end

  # Additional functionality

  def reload_fields(conn, %{"id" => id}) do
    data_set = DataSetActions.get!(id)

    conn =
      case data_set.state do
        "new" ->
          FieldActions.list(for_data_set: data_set)
          |> Enum.each(&FieldActions.delete/1)

          FieldActions.create_for_data_set(data_set)

          put_flash(conn, :info, "Fields have been reloaded")

        _ ->
          put_flash(conn, :error, "Cannot reload fields when no longer new")
      end

    redirect(conn, to: Routes.data_set_path(conn, :show, data_set))
  end

  def submit_for_approval(conn, %{"id" => id}) do
    data_set = DataSetActions.get!(id)

    conn =
      case data_set.state do
        "new" ->
          {:ok, _} = DataSetActions.update(data_set, state: "awaiting_approval")
          put_flash(conn, :success, "#{data_set.name} has been submitted for approval")

        _ ->
          put_flash(conn, :error, "Cannot submit non-new data sets for approval")
      end

    redirect(conn, to: Routes.data_set_path(conn, :show, data_set))
  end

  def ingest_now(conn, %{"id" => id}) do
    data_set = DataSetActions.get!(id)
    :ok = Etl.import_data_set_on_demand(data_set)

    conn
    |> put_flash(:info, "#{data_set.name} has been added to the ingest queue")
    |> redirect(to: Routes.data_set_path(conn, :show, data_set))
  end
end

lib/plenario_web/views/data_set_view.ex
defmodule PlenarioWeb.DataSetView do
  use PlenarioWeb, :view

  import Plenario.DataSet, only: [
    refresh_interval_choices: 0,
    src_type_choices: 0
  ]
end

lib/plenario_web/templates/data_set/_socrata_form.html.eex
<div class="form-group">
  <%= label @f, "Socrata Domain", class: "control-label" %>
  <%= text_input @f, :soc_domain, class: "form-control", placeholder: "data.cityofchicago.org", disabled: not @fully_editable? %>
  <%= error_tag @f, :soc_domain %>
</div>

<div class="form-group">
  <%= label @f, "Socrata 4x4", class: "control-label" %>
  <%= text_input @f, :soc_4x4, class: "form-control", placeholder: "abcd-1234", disabled: not @fully_editable? %>
  <%= error_tag @f, :soc_4x4 %>
</div>

<%= hidden_input @f, :src_type, value: "json" %>

lib/plenario_web/templates/data_set/_web_resource_form.html.eex
<div class="form-group">
  <%= label @f, "Source URL", class: "control-label" %>
  <%= text_input @f, :src_url, class: "form-control", placeholder: "https://example.com/test.csv", disabled: not @fully_editable? %>
  <%= error_tag @f, :src_url %>
</div>

<div class="form-group">
  <%= label @f, "Source Type", class: "control-label" %>
  <%= select @f, :src_type, src_type_choices(), class: "form-control", value: "csv", disabled: not @fully_editable? %>
  <%= error_tag @f, :src_type %>
</div>

lib/plenario_web/templates/data_set/edit.html.eex
<div class="container mt-2">
  <h1>Edit <%= @data_set %></h1>

  <%= render "form.html", changeset: @changeset, action: @update_action, fully_editable?: @fully_editable? %>
</div>

lib/plenario_web/templates/data_set/form.html.eex
<%# 
    PARAMS THAT NEED TO BE SET:

    changeset: the form changeset
    action: the form action
%>

<%= form_for @changeset, @action, fn f -> %>

<%= hidden_input f, :user_id, value: Ecto.Changeset.get_field(f.source, :user_id) %>
<%= hidden_input f, :socrata?, value: Ecto.Changeset.get_field(f.source, :socrata?) %>
<%= hidden_input f, :state, value: Ecto.Changeset.get_field(f.source, :state) %>

<div class="form-group">
  <%= label f, :name, class: "control-label" %>
  <%= text_input f, :name, class: "form-control", disabled: not @fully_editable? %>
  <%= error_tag f, :name %>
</div>

<%= case Ecto.Changeset.get_field(f.source, :socrata?) do
  true -> render "_socrata_form.html", f: f, fully_editable?: @fully_editable?
  false -> render "_web_resource_form.html", f: f, fully_editable?: @fully_editable?
end %>

<div class="form-group">
  <%= label f, :attribution, class: "control-label" %>
  <%= text_input f, :attribution, class: "form-control", placeholder: "City of Chicago" %>
  <%= error_tag f, :attribution %>
</div>

<div class="form-group">
  <%= label f, :description, class: "control-label" %>
  <%= textarea f, :description, class: "form-control", placeholder: "Long form description of the data set" %>
  <%= error_tag f, :description %>
</div>

<div class="form-group">
  <%= label f, :refresh_starts_on, class: "control-label" %>
  <%= date_input f, :refresh_starts_on, class: "form-control" %>
  <%= error_tag f, :refresh_starts_on %>
</div>

<div class="form-group">
  <%= label f, :refresh_ends_on, class: "control-label" %>
  <%= date_input f, :refresh_ends_on, class: "form-control" %>
  <%= error_tag f, :refresh_ends_on %>
</div>

<div class="form-group">
  <%= label f, :refresh_interval, class: "control-label" %>
  <%= select f, :refresh_interval, refresh_interval_choices(), class: "form-control" %>
  <%= error_tag f, :refresh_interval %>
</div>

<div class="form-group">
  <%= label f, :refresh_rate, class: "control-label" %>
  <%= number_input f, :refresh_rate, class: "form-control" %>
  <%= error_tag f, :refresh_rate %>
</div>

<div class="form-group">
  <%= submit "Submit", class: "btn btn-primary" %>
</div>

<% end %>

lib/plenario_web/templates/data_set/index.html.eex
<h1>Listing Data sets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Slug</th>
      <th>Table name</th>
      <th>View name</th>
      <th>State</th>
      <th>Soc domain</th>
      <th>Soc 4x4</th>
      <th>Src url</th>
      <th>Src type</th>
      <th>Socrata?</th>
      <th>Attribution</th>
      <th>Description</th>
      <th>Refresh starts on</th>
      <th>Refresh ends on</th>
      <th>Refresh interval</th>
      <th>Refresh rate</th>
      <th>First import</th>
      <th>Next import</th>
      <th>Bbox</th>
      <th>Hull</th>
      <th>Time range</th>
      <th>Num records</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for data_set <- @data_sets do %>
    <tr>
      <td><%= data_set.name %></td>
      <td><%= data_set.slug %></td>
      <td><%= data_set.table_name %></td>
      <td><%= data_set.view_name %></td>
      <td><%= data_set.state %></td>
      <td><%= data_set.soc_domain %></td>
      <td><%= data_set.soc_4x4 %></td>
      <td><%= data_set.src_url %></td>
      <td><%= data_set.src_type %></td>
      <td><%= data_set.socrata? %></td>
      <td><%= data_set.attribution %></td>
      <td><%= data_set.description %></td>
      <td><%= data_set.refresh_starts_on %></td>
      <td><%= data_set.refresh_ends_on %></td>
      <td><%= data_set.refresh_interval %></td>
      <td><%= data_set.refresh_rate %></td>
      <td><%= data_set.first_import %></td>
      <td><%= data_set.next_import %></td>
      <td><%= data_set.bbox %></td>
      <td><%= data_set.hull %></td>
      <td><%= data_set.time_range %></td>
      <td><%= data_set.num_records %></td>

      <td>
        <%= link "Show", to: Routes.data_set_path(@conn, :show, data_set) %>
        <%= link "Edit", to: Routes.data_set_path(@conn, :edit, data_set) %>
        <%= link "Delete", to: Routes.data_set_path(@conn, :delete, data_set), method: :delete, data: [confirm: "Are you sure?"] %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Data set", to: Routes.data_set_path(@conn, :new) %></span>

lib/plenario_web/templates/data_set/show.html.eex
<div class="container mt-2">
  <h2>
    <%= @data_set.name %>
    
    <%= if @user_is_owner? do %>
      <%= button "Delete", to: Routes.data_set_path(@conn, :delete, @data_set), method: :delete, class: "btn btn-primary float-right", style: "margin-left: 10px", data: [confirm: "Are you sure?"] %>
    <% end %>
    
    <%= if @user_is_owner? and @submittable? do %>
      <%= button "Submit for Approval", to: Routes.data_set_path(@conn, :submit_for_approval, @data_set), class: "btn btn-success float-right", style: "margin-left: 10px" %>
    <% end %>
    
    <%= if @user_is_owner? and @ok_to_import? do %>
      <%= button "Import Now", to: Routes.data_set_path(@conn, :ingest_now, @data_set), class: "btn btn-info float-right", style: "margin-left: 10px" %>
    <% end %>
    
    <%= if not @submittable? and @user_is_owner? do %>
      <%# link "Request Changes", to: Routes.data_set_path(@conn, :request_changes, @data_set), class: "btn btn-warning float-right", style: "margin-left: 10px" %>
    <% end %>
  </h2>

  <hr>

  <div class="row">
    <div class="col-lg-12">
      <h3>
        General Info
        <%= if @user_is_owner? do %>
          <%= link "Edit", to: Routes.data_set_path(@conn, :edit, @data_set), class: "btn btn-success float-right" %>
        <% end %>
      </h3>
      <table class="table table-striped">
        <tbody>
          <tr>
            <td>Name:</td>
            <td>
              <%= @data_set.name %>
            </td>
          </tr>
          <tr>
            <td>Status:</td>
            <td>
              <%= @data_set.state %>
            </td>
          </tr>
          <tr>
            <td>Contributor:</td>
            <td>
              <%= @data_set.user.username %>
            </td>
          </tr>
          <tr>
            <td>Description:</td>
            <td><span style="white-space: pre-line;">
                <%= @data_set.description %></span></td>
          </tr>
          <tr>
            <td>Attribution:</td>
            <td>
              <%= @data_set.attribution %>
            </td>
          </tr>
          <%= if @data_set.socrata? do %>
          <tr>
            <td>Socrata Domain:</td>
            <td><%= @data_set.soc_domain %></td>
          </tr>
          <tr>
            <td>Socrata 4x4:</td>
            <td><%= @data_set.soc_4x4 %></td>
          </tr>
          <% else %>
          <tr>
            <td>Source URL:</td>
            <td><%= @data_set.src_url %></td>
          </tr>
          <% end %>
          <tr>
            <td>Refresh Cadence:</td>
            <td>
              <%= format_refresh_cadence(@data_set) %>
            </td>
          </tr>
          <tr>
            <td>Refresh Starts On:</td>
            <td><%= @data_set.refresh_starts_on %></td>
          </tr>
          <tr>
            <td>Refresh Ends On:</td>
            <td>
              <%= @data_set.refresh_ends_on %>
            </td>
          </tr>
          <tr>
            <td>First Import:</td>
            <td>
              <%= @data_set.first_import %>
            </td>
          </tr>
          </tr>
          <tr>
            <td>Latest Import:</td>
            <td>
              <%= @data_set.latest_import %>
            </td>
          </tr>
          </tr>
          <tr>
            <td>Next Import:</td>
            <td>
              <%= @data_set.next_import %>
            </td>
          </tr>
          <tr>
            <td>Time Range:</td>
            <td>
              <%= @data_set.time_range %>
            </td>
          </tr>
          <tr>
            <td>Number of Records:</td>
            <td>
              <%= @data_set.num_records %>
            </td>
          </tr>
        </tbody>
      </table>
    </div> <!-- General Info -->
  </div>

  <hr>
  
  <div class="row">
    <div class="col-lg-12">
      <h3>
        Data Set Fields
        <%= if @user_is_owner? and @submittable? do %>
          <%= button "Delete and Reload Fields", to: Routes.data_set_path(@conn, :reload_fields, @data_set), class: "btn btn-primary float-right" %>
        <% end %>
      </h3>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Name</th>
            <th>Type</th>
            <th>Description</th>
            <%= if @user_is_owner? do %>
              <th></th>
            <% end %>
          </tr>
        </thead>
        <tbody>
          <%= for f <- @data_set.fields do %>
          <tr>
            <td>
              <%= f.name %>
            </td>
            <td>
              <%= f.type %>
            </td>
            <td style="max-width: 6em; word-wrap: break-word;">
              <%= f.description %>
            </td>
            <%= if @user_is_owner? do %>
              <td>
              <%= link "Edit", to: Routes.data_set_field_path(@conn, :edit, @data_set.id, f), class: "btn btn-success btn-sm float-right" %>
            </td>
            <% end %>
            <% end %>
        </tbody>
      </table> <!-- .table.table-striped -->
    </div>
  </div>

  <hr>

  <div class="row">
    <div class="col-lg-12">
      <h3>
        Computed Date Fields
        <%# tooltip "A composite field constructed from discrete fields in the data set: if the data set contains separate fields for, say, year, month and day, we can construct a single date field to index to better query the data." %>
        <%= if @user_is_owner? and @submittable? do %>
          <%= link "Add a New Date Field", to: Routes.data_set_virtual_date_path(@conn, :new, @data_set.id), class: "btn btn-success float-right" %>
        <% end %>
      </h3>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Year Ref</th>
            <th>Month Ref</th>
            <th>Day Ref</th>
            <th>Hour Ref</th>
            <th>Minute Ref</th>
            <th>Second Ref</th>
            <%= if @user_is_owner? and @submittable? do %>
              <th></th>
            <% end %>
          </tr>
        </thead>
        <tbody>
          <%= for f <- @virtual_dates do %>
          <tr>
            <td>
              <%= f.yr_field.col_name %>
            </td>
            <td>
              <%= if f.mo_field do %>
              <%= f.mo_field.col_name %>
              <% else %>-
              <% end %>
            </td>
            <td>
              <%= if f.day_field do %>
              <%= f.day_field.col_name %>
              <% else %>-
              <% end %>
            </td>
            <td>
              <%= if f.hr_field do %>
              <%= f.hr_field.col_name %>
              <% else %>-
              <% end %>
            </td>
            <td>
              <%= if f.min_field do %>
              <%= f.min_field.col_name %>
              <% else %>-
              <% end %>
            </td>
            <td>
              <%= if f.sec_field do %>
              <%= f.sec_field.col_name %>
              <% else %>-
              <% end %>
            </td>
            <%= if @user_is_owner? and @submittable? do %>
              <td>
                <%= link "Delete", to: Routes.data_set_virtual_date_path(@conn, :delete, @data_set.id, f.id), method: :delete, class: "btn btn-primary btn-sm", style: "margin-left: 10px" %>
                <%= link "Edit", to: Routes.data_set_virtual_date_path(@conn, :edit, @data_set.id, f.id), class: "btn btn-success btn-sm", style: "margin-left: 10px" %>
            </td>
            <% end %>
            <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <hr>

  <div class="row">
    <div class="col-lg-12">
      <h3>
        Computed Point Fields
        <%# tooltip "A location field constructed from primitive fields in the data set: if the data set contains a single or separate fields that represent coordinate points, we can derive a coordinate field." %>
        <%= if @user_is_owner? and @submittable? do %>
          <%= link "Add a New Point Field", to: Routes.data_set_virtual_point_path(@conn, :new, @data_set.id), class: "btn btn-success float-right" %>
        <% end %>
      </h3>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Location Ref</th>
            <th>Latitude Ref</th>
            <th>Longitude Ref</th>
            <%= if @user_is_owner? and @submittable? do %>
              <th></th>
            <% end %>
          </tr>
        </thead>
        <tbody>
          <%= for f <- @virtual_points do %>
          <tr>
            <td>
              <%= if f.loc_field do %>
              <%= f.loc_field.col_name %>
              <% else %>-
              <% end %>
            </td>
            <td>
              <%= if f.lat_field do %>
              <%= f.lat_field.col_name %>
              <% else %>-
              <% end %>
            </td>
            <td>
              <%= if f.lon_field do %>
              <%= f.lon_field.col_name %>
              <% else %>-
              <% end %>
            </td>
            <%= if @user_is_owner? and @submittable? do %>
              <td>
                <%= link "Delete", to: Routes.data_set_virtual_point_path(@conn, :delete, @data_set.id, f.id), method: :delete, class: "btn btn-primary btn-sm", style: "margin-left: 10px" %>
                <%= link "Edit", to: Routes.data_set_virtual_point_path(@conn, :edit, @data_set.id, f.id), class: "btn btn-success btn-sm", style: "margin-left: 10px" %>
            </td>
            <% end %>
            <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>