lib/plenario_web/router.ex
defmodule PlenarioWeb.Router do
  use PlenarioWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :maybe_auth do
    plug PlenarioWeb.AuthPipeline
    plug PlenarioWeb.CurrentUserPlug
  end

  pipeline :ensure_auth do
    plug PlenarioWeb.AuthPipeline
    plug Guardian.Plug.EnsureAuthenticated
    plug PlenarioWeb.CurrentUserPlug
  end

  pipeline :admin do
    plug PlenarioWeb.AuthPipeline
    plug Guardian.Plug.EnsureAuthenticated
    plug PlenarioWeb.EnsureAdminPlug
    plug PlenarioWeb.CurrentUserPlug
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", PlenarioWeb do
    pipe_through ~w|browser ensure_auth|a

    # me controller
    get "/me",        MeController, :show
    get "/me/edit",   MeController, :edit
    put "/me/update", MeController, :update

    # data sets
    resources "/data-sets", DataSetController, only: ~w|new create edit update delete|a
    post "/data-sets/:id/submit-for-approval", DataSetController, :submit_for_approval
    post "/data-sets/:id/reload-fields", DataSetController, :reload_fields
    post "/data-sets/:id/ingest-now", DataSetController, :ingest_now

    # data set nested resources: fields, virtual dates and virtual points
    resources "/data-sets", DataSetController do
      # fields
      resources "/fields", FieldController, only: ~w|edit update delete|a
      # virtual dates
      resources "/virtual-dates", VirtualDateController, only: ~w|new create edit update delete|a
      # virtual points
      resources "/virtual-points", VirtualPointController, only: ~w|new create edit update delete|a
    end
  end

  scope "/", PlenarioWeb do
    pipe_through ~w|browser maybe_auth|a

    # flat page
    get "/", PageController, :index
    get "/explorer", PageController, :explorer

    # sessions
    get   "/login",     SessionController, :login
    post  "/login",     SessionController, :login
    get   "/register",  SessionController, :register
    post  "/register",  SessionController, :register
    post  "/logout",    SessionController, :logout

    # data sets
    get "/data-sets/:id", DataSetController, :show
  end

  scope "/admin", PlenarioWeb do
    pipe_through ~w|browser admin|a

    get "/", PageAdminController, :index

    resources "/users", UserAdminController

    get "/data-sets",               DataSetAdminController, :index
    get "/data-sets/:id/review",    DataSetAdminController, :review
    post "/data-sets/:id/approve",  DataSetAdminController, :approve
    post "/data-sets/:id/reject",   DataSetAdminController, :reject
  end

  scope "/api/v2", PlenarioWeb do
    pipe_through [:api]

    get "/data-sets", DataSetApiController, :list
    get "/data-sets/:slug", DataSetApiController, :detail
    get "/data-sets/:slug/@aggregate", DataSetApiController, :aggregate
  end
end

lib/plenario_web/views/layout_view.ex
defmodule PlenarioWeb.LayoutView do
  use PlenarioWeb, :view
end

lib/plenario_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Plenario</title>

    <!-- Import css and js files built by Webpack -->
    <link rel="stylesheet" href='<%= Routes.static_path(@conn, "/css/main.css") %>'>
    <script src='<%= Routes.static_path(@conn, "/js/polyfill.bundle.js") %>'></script>
    <script src='<%= Routes.static_path(@conn, "/js/main.bundle.js") %>'></script>
    <link rel="shortcut icon" type="image/png" href='<%= Routes.static_path(@conn, "/images/favicon.png") %>'>
  </head>

  <body>
    <%= render "flashes.html", assigns %>
    <%= 
      case @admin_nav? do 
        true -> render "navbar-admin.html", assigns
        false -> render "navbar-main.html", assigns
      end
    %>
    <main role="main">
      <%= render @view_module, @view_template, assigns %>
    </main>
  </body>
</html>

lib/plenario_web/templates/layout/flashes.html.eex
<div class="container flash-container">
  <%= if get_flash(@conn, :info) do %>
  <div class="alert alert-info alert-dismissible fade show" role="alert">
    <%= get_flash(@conn, :info) %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <% end %>
  <%= if get_flash(@conn, :success) do %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= get_flash(@conn, :success) %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <% end %>
  <%= if get_flash(@conn, :error) do %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <%= get_flash(@conn, :error) %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <% end %>
</div>

lib/plenario_web/templates/layout/navbar-admin.html.eex
<nav id="main-nav" class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">

  <div class="container">

    <%= link to: Routes.page_admin_path(@conn, :index), class: "navbar-brand" do %>
      <img class="logo" src="/images/arch.svg" alt=""> Plenario Admin
    <% end %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main-nav-collapsible"
      aria-controls="main-nav-collapsible" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div id="main-nav-collapsible" class="collapse navbar-collapse">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <%= link "Admin Home", to: Routes.page_admin_path(@conn, :index), class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link "Users", to: Routes.user_admin_path(@conn, :index), class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link "Data Sets", to: Routes.data_set_admin_path(@conn, :index), class: "nav-link" %>
        </li>
        <li class="nav-item d-md-none">
          <%= link raw("<i class=\"fas fa-sign-out-alt\"></i> Exit"), to: Routes.page_path(@conn, :index), class: "nav-link text-danger" %>
        </li>
      </ul>
      <div class="inline-form d-none d-md-inline ml-md-2">
        <%= link raw("Exit <i class=\"fas fa-sign-out-alt\"></i>"), to: Routes.page_path(@conn, :index), class: "btn btn-danger btn-sm" %>
      </div>
    </div>

  </div>

</nav>

lib/plenario_web/templates/layout/navbar-hero.html.eex
<div class="container">

  <div class="navbar navbar-expand px-0">

    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a href="https://plenario.docs.apiary.io" target="_blank" class="nav-link">API</a>
      </li>
      <li class="nav-item">
        <a href="https://github.com/UrbanCCD-UChicago/plenario2" target="_blank" class="nav-link"><i title="Contribute on GitHub"
            class="fab fa-github fa-lg"></i></a>
      </li>
    </ul>

    <div class="inline-form ml-md-2">
      <%= if @current_user do %>
      <div class="btn-group">
        <%= link "User Dashboard", to: Routes.me_path(@conn, :show), class: "btn btn-outline-info btn-sm" %>
        <button type="button" class="btn btn-outline-info btn-sm dropdown-toggle dropdown-toggle-split" data-toggle="dropdown"
          aria-haspopup="true" aria-expanded="false">
          <span class="sr-only">Toggle Dropdown</span>
        </button>
        <div class="dropdown-menu dropdown-menu-right bg-dark text-white p-1">
          <%= link raw("<i class=\"fas fa-sign-out-alt\"></i> Log Out"), to: Routes.session_path(@conn, :logout), method: :post, class: "dropdown-item text-center" %>
        </div>
      </div>
      <%= if @current_user.is_admin? do %>
      <%= link raw("<i class=\"fas fa-lock\"></i> Admin"), to: Routes.page_admin_path(@conn, :index), class: "btn btn-outline-danger btn-sm" %>
      <% end %>
      <% else %>
      <%= link "Sign Up / Log In", to: Routes.session_path(@conn, :login), class: "btn btn-outline-success btn-sm" %>
      <% end %>
    </div>

  </div>

</div>

lib/plenario_web/templates/layout/navbar-main.html.eex
<nav id="main-nav" class="navbar navbar-expand-md navbar-light bg-light fixed-top">

  <div class="container">

    <%= link to: Routes.page_path(@conn, :index), class: "navbar-brand" do %>
    <img class="logo" src="/images/arch.svg" alt=""> Plenario
    <% end %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main-nav-collapsible"
      aria-controls="main-nav-collapsible" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div id="main-nav-collapsible" class="collapse navbar-collapse">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <%= link "Explore", to: Routes.page_path(@conn, :explorer), class: "nav-link" %>
        </li>
        <li class="nav-item">
          <a href="https://plenario.docs.apiary.io" target="_blank" class="nav-link">API</a>
        </li>
        <li class="nav-item">
          <a href="https://github.com/UrbanCCD-UChicago/plenario2" target="_blank" class="nav-link">
            <i title="Contribute on GitHub" class="fab fa-github fa-lg"></i>
            <span class="d-md-none">Contribute on GitHub</span>
          </a>
        </li>
        <li class="nav-item d-md-none">
          <%= if @current_user do %>
          <%= link "User Dashboard", to: Routes.me_path(@conn, :show), class: "nav-link" %>
          <%= link raw("<i class='fas fa-sign-out-alt'></i> Log Out"), to: Routes.session_path(@conn, :logout), method: :post, class: "nav-link" %>
          <%= if @current_user.is_admin? do %>
          <%= link raw("<i class='fas fa-lock'></i> Admin"), to: Routes.page_admin_path(@conn, :index), class: "nav-link" %>
          <% end %>
          <% else %>
          <%= link "Sign Up / Log In", to: Routes.session_path(@conn, :login), class: "nav-link" %>
          <% end %>
        </li>
      </ul>
      <div class="inline-form d-none d-md-inline ml-md-2">
        <%= if @current_user do %>
        <div class="btn-group">
          <%= link "User Dashboard", to: Routes.me_path(@conn, :show), class: "btn btn-info btn-sm" %>
          <button type="button" class="btn btn-info btn-sm dropdown-toggle dropdown-toggle-split" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            <span class="sr-only">Toggle Dropdown</span>
          </button>
          <div class="dropdown-menu dropdown-menu-right p-1">
            <%= link raw("<i class='fas fa-sign-out-alt'></i> Log Out"), to: Routes.session_path(@conn, :logout), method: :post, class: "dropdown-item text-center" %>
          </div>
        </div>
        <%= if @current_user.is_admin? do %>
        <%= link raw("<i class='fas fa-lock'></i> Admin"), to: Routes.page_admin_path(@conn, :index), class: "btn btn-danger btn-sm" %>
        <% end %>
        <% else %>
        <%= link "Sign Up / Log In", to: Routes.session_path(@conn, :login), class: "btn btn-success btn-sm" %>
        <% end %>
      </div>
    </div>

  </div>

</nav>