lib/plenario_web/router.ex
defmodule PlenarioWeb.Router do
  use PlenarioWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :maybe_auth do
    plug PlenarioWeb.AuthPipeline
    plug PlenarioWeb.CurrentUserPlug
  end

  pipeline :ensure_auth do
    plug PlenarioWeb.AuthPipeline
    plug Guardian.Plug.EnsureAuthenticated
    plug PlenarioWeb.CurrentUserPlug
  end

  pipeline :admin do
    plug PlenarioWeb.AuthPipeline
    plug Guardian.Plug.EnsureAuthenticated
    plug PlenarioWeb.EnsureAdminPlug
    plug PlenarioWeb.CurrentUserPlug
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", PlenarioWeb do
    pipe_through ~w|browser ensure_auth|a

    # me controller
    get "/me",        MeController, :show
    get "/me/edit",   MeController, :edit
    put "/me/update", MeController, :update

    # data sets
    resources "/data-sets", DataSetController, only: ~w|new create edit update delete|a
    post "/data-sets/:id/submit-for-approval", DataSetController, :submit_for_approval
    post "/data-sets/:id/reload-fields", DataSetController, :reload_fields
    post "/data-sets/:id/ingest-now", DataSetController, :ingest_now

    # data set nested resources: fields, virtual dates and virtual points
    resources "/data-sets", DataSetController do
      # fields
      resources "/fields", FieldController, only: ~w|edit update delete|a
      # virtual dates
      resources "/virtual-dates", VirtualDateController, only: ~w|new create edit update delete|a
      # virtual points
      resources "/virtual-points", VirtualPointController, only: ~w|new create edit update delete|a
    end
  end

  scope "/", PlenarioWeb do
    pipe_through ~w|browser maybe_auth|a

    # flat page
    get "/", PageController, :index
    get "/explorer", PageController, :explorer

    # sessions
    get   "/login",     SessionController, :login
    post  "/login",     SessionController, :login
    get   "/register",  SessionController, :register
    post  "/register",  SessionController, :register
    post  "/logout",    SessionController, :logout

    # data sets
    get "/data-sets/:id", DataSetController, :show
  end

  scope "/admin", PlenarioWeb do
    pipe_through ~w|browser admin|a

    get "/", PageAdminController, :index

    resources "/users", UserAdminController

    get "/data-sets",               DataSetAdminController, :index
    get "/data-sets/:id/review",    DataSetAdminController, :review
    post "/data-sets/:id/approve",  DataSetAdminController, :approve
    post "/data-sets/:id/reject",   DataSetAdminController, :reject
  end

  scope "/api/v2", PlenarioWeb do
    pipe_through [:api]

    get "/data-sets", DataSetApiController, :list
    get "/data-sets/:slug", DataSetApiController, :detail
    get "/data-sets/:slug/@aggregate", DataSetApiController, :aggregate
  end
end

lib/plenario_web/controllers/data_set_admin_controller.ex
defmodule PlenarioWeb.DataSetAdminController do
  use PlenarioWeb, :controller

  require Logger

  alias Plenario.{
    DataSetActions,
    VirtualDateActions,
    VirtualPointActions,
    Repo
  }

  def index(conn, _) do
    data_sets = DataSetActions.list(with_user: true)

    erred = Enum.filter(data_sets, & &1.state == "erred")
    approval = Enum.filter(data_sets, & &1.state == "awaiting_approval")
    first = Enum.filter(data_sets, & &1.state == "awaiting_first_import")
    live = Enum.filter(data_sets, & &1.state == "ready")

    render conn, "index.html",
      erred: erred,
      approval: approval,
      first: first,
      live: live
  end

  def review(conn, %{"id" => id}) do
    data_set = DataSetActions.get!(id, with_user: true, with_fields: true)
    dates = VirtualDateActions.list(for_data_set: data_set, with_fields: true)
    points = VirtualPointActions.list(for_data_set: data_set, with_fields: true)

    approve_action = Routes.data_set_admin_path(conn, :approve, data_set)
    reject_action = Routes.data_set_admin_path(conn, :reject, data_set)

    render conn, "review.html",
      data_set: data_set,
      dates: dates,
      points: points,
      approve_action: approve_action,
      reject_action: reject_action
  end

  def approve(conn, %{"id" => id}) do
    data_set = DataSetActions.get!(id)

    conn =
      try do
        :ok = Repo.up!(data_set)
        {:ok, _} = DataSetActions.update(data_set, state: "awaiting_first_import")
        conn
      rescue
        e in Exception ->
          Logger.error(e.message)
          put_flash(conn, :error, e.message)
      end

    redirect(conn, to: Routes.data_set_admin_path(conn, :index))
  end

  def reject(conn, %{"id" => id}) do
    data_set = DataSetActions.get!(id)
    {:ok, _} = DataSetActions.update(data_set, state: "new")

    redirect(conn, to: Routes.data_set_admin_path(conn, :index))
  end
end

lib/plenario_web/views/data_set_admin_view.ex
defmodule PlenarioWeb.DataSetAdminView do
  use PlenarioWeb, :view
end

lib/plenario_web/templates/data_set_admin/index.html.eex
<div class="container mt-2">

  <h1>Data Set Admin</h1>

  <%= if length(@erred) > 0 do %>
  <div class="row">
    <h2>
      <%= length(@erred) %> Erred
    </h2>

    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Contributor</th>
          <th>Description</th>
        </tr>
      </thead>
      <tbody>
        <%= for d <- @erred do %>
        <tr>
          <td><%= d.name %></td>
          <td><%= d.user.username %></td>
          <td><%= d.description %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <% end %>

  <%= if length(@approval) > 0 do %>
  <div class="row">
    <h2>
      <%= length(@approval) %> Need Approval
    </h2>

    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Contributor</th>
          <th>Description</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <%= for d <- @approval do %>
        <tr>
          <td><%= d.name %></td>
          <td><%= d.user.username %></td>
          <td><%= d.description %></td>
          <td><%= link "Review", to: Routes.data_set_admin_path(@conn, :review, d), class: "btn btn-sm btn-success float-right" %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <% end %>

  <%= if length(@first) > 0 do %>
  <div class="row">
    <h2>
      <%= length(@first) %> Awaiting First Import
    </h2>
  
    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Contributor</th>
          <th>Description</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <%= for d <- @first do %>
        <tr>
          <td><%= d.name %></td>
          <td><%= d.user.username %></td>
          <td><%= d.description %></td>
          <td><%= button "Import Now", to: Routes.data_set_path(@conn, :ingest_now, d), class: "btn btn-sm btn-success float-primary" %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <% end %>

  <%= if length(@live) > 0 do %>
  <div class="row">
    <h2>
      <%= length(@live) %> Live
    </h2>
  
    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Contributor</th>
          <th>Description</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <%= for d <- @live do %>
        <tr>
          <td><%= d.name %></td>
          <td><%= d.user.username %></td>
          <td><%= d.description %></td>
          <td>
            <%= link "View/Edit", to: Routes.data_set_path(@conn, :edit, d), class: "btn btn-sm btn-info float-right", style: "margin-left: 10px" %>
            <%= button "Import Now", to: Routes.data_set_path(@conn, :ingest_now, d), class: "btn btn-sm btn-success float-right" %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <% end %>

</div>

lib/plenario_web/templates/data_set_admin/review.html.eex
<div class="container mt-2">
  <h2>
    Review <%= @data_set.name %>
    <div id="meta-buttons">
      <%= button "Approve", to: @approve_action, class: "btn btn-success" %>
      <%= button "Reject", to: @reject_action, class: "btn btn-danger" %>
    </div>
  </h2>

  <hr>

  <div class="row">
    <div class="col-lg-12">
      <h3>General Info</h3>
      
      <table class="table table-striped">
        <tbody>
          <tr>
            <td>Name:</td>
            <td>
              <%= @data_set.name %>
            </td>
          </tr>
          <tr>
            <td>Status:</td>
            <td>
              <%= @data_set.state %>
            </td>
          </tr>
          <tr>
            <td>Contributor:</td>
            <td>
              <%= @data_set.user.username %>
            </td>
          </tr>
          <tr>
            <td>Description:</td>
            <td><span style="white-space: pre-line;">
                <%= @data_set.description %></span></td>
          </tr>
          <tr>
            <td>Attribution:</td>
            <td>
              <%= @data_set.attribution %>
            </td>
          </tr>
          <%= if @data_set.socrata? do %>
          <tr>
            <td>Socrata Domain:</td>
            <td>
              <%= @data_set.soc_domain %>
            </td>
          </tr>
          <tr>
            <td>Socrata 4x4:</td>
            <td>
              <%= @data_set.soc_4x4 %>
            </td>
          </tr>
          <% else %>
          <tr>
            <td>Source URL:</td>
            <td>
              <%= @data_set.src_url %>
            </td>
          </tr>
          <% end %>
          <tr>
            <td>Refresh Cadence:</td>
            <td>
              <%= format_refresh_cadence(@data_set) %>
            </td>
          </tr>
          <tr>
            <td>First Import:</td>
            <td>
              <%= @data_set.first_import %>
            </td>
          </tr>
          </tr>
          <tr>
            <td>Latest Import:</td>
            <td>
              <%= @data_set.latest_import %>
            </td>
          </tr>
          </tr>
          <tr>
            <td>Next Import:</td>
            <td>
              <%= @data_set.next_import %>
            </td>
          </tr>
          <tr>
            <td>Time Range:</td>
            <td>
              <%= @data_set.time_range %>
            </td>
          </tr>
          <tr>
            <td>Number of Records:</td>
            <td>
              <%= @data_set.num_records %>
            </td>
          </tr>
        </tbody>
      </table>
    </div> <!-- General Info -->
  </div>

  <div class="row">
    <div class="col-lg-12">
      <h3>
        Fields
      </h3>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Name</th>
            <th>Type</th>
            <th>Description</th>
          </tr>
        </thead>
        <tbody>
          <%= for f <- @data_set.fields do %>
          <tr>
            <td>
              <%= f.name %>
            </td>
            <td>
              <%= f.type %>
            </td>
            <td style="max-width: 6em; word-wrap: break-word;">
              <%= f.description %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table> <!-- .table.table-striped -->
    </div>
  </div>

  <div class="row">
    <div class="col-lg-12">
      <h3>
        Virtual Dates
      </h3>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Col Name</th>
            <th>Year Ref</th>
            <th>Month Ref</th>
            <th>Day Ref</th>
            <th>Hour Ref</th>
            <th>Minute Ref</th>
            <th>Second Ref</th>
          </tr>
        </thead>
        <tbody>
          <%= for f <- @dates do %>
          <tr>
            <td><%= f.col_name %></td>
            <td>
              <%= f.yr_field.col_name %>
            </td>
            <td>
              <%= if f.mo_field do %>
              <%= f.mo_field.col_name %>
              <% else %>-
              <% end %>
            </td>
            <td>
              <%= if f.day_field do %>
              <%= f.day_field.col_name %>
              <% else %>-
              <% end %>
            </td>
            <td>
              <%= if f.hr_field do %>
              <%= f.hr_field.col_name %>
              <% else %>-
              <% end %>
            </td>
            <td>
              <%= if f.min_field do %>
              <%= f.min_field.col_name %>
              <% else %>-
              <% end %>
            </td>
            <td>
              <%= if f.sec_field do %>
              <%= f.sec_field.col_name %>
              <% else %>-
              <% end %>
            </td>
            <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-12">
      <h3>
        Virtual Points
      </h3>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Col Name</th>
            <th>Location Ref</th>
            <th>Latitude Ref</th>
            <th>Longitude Ref</th>
          </tr>
        </thead>
        <tbody>
          <%= for f <- @points do %>
          <tr>
            <td><%= f.col_name %></td>
            <td>
              <%= if f.loc_field do %>
              <%= f.loc_field.col_name %>
              <% else %>-
              <% end %>
            </td>
            <td>
              <%= if f.lat_field do %>
              <%= f.lat_field.col_name %>
              <% else %>-
              <% end %>
            </td>
            <td>
              <%= if f.lon_field do %>
              <%= f.lon_field.col_name %>
              <% else %>-
              <% end %>
            </td>
            <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>